export const requests = {
    login: '/auth/login',
    logout: '/user/logout',
    signup: '/auth/signup',
    likeTweet: '/tweets/like/',
    editTweet: '/tweets/edit/',
    incrementViews: '/tweets/increment-views/',
    deleteTweet: '/tweets/delete/',
    getTweet: '/tweets/fetch/',
    liveFeed: '/tweets/livefeed',
    bookmarkTweet: '/bookmarks/add/',
    deleteBookmark: '/bookmarks/delete/',
    getBookmarks: '/bookmarks/',
    voteOnPoll: '/tweets/poll/vote',
    getTweetComments: '/comments/get/',
    postComment: '/comments/',
    postNotification: '/notifications/create',
    getNotifications: '/notifications/',
    postTweet: '/tweets/tweet',
    likeComment: '/comments/like/',
};
